export const GET_ALL_CATEGORIES_API_URL = "category/";
export const CATEGORY_TITLE = "Categorías";
export const MAX_CATEGORIES_PER_SLIDE_MOBILE = 4;
export const MAX_CATEGORIES_PER_SLIDE_DESKTOP = 8;
export const CATEGORY_SLIDE_SPACE_BETWEEN_ITEMS_MOBILE = 10;
export const CATEGORY_SLIDE_SPACE_BETWEEN_ITEMS_DESKTOP = 5;
